ghost:
  all:
    num_classes: 100 #10177
    dropout: 0.0
    lr: 1e-2
    wd: 1e-4
    momentum: 0.9
  init_1.0:
    width: 1.0
  init_1.3:
    width: 1.3
  init_1.6:
    width: 1.6
  softmax_1.0:
    width: 1.0
    lr: 1e-3
    wd: 0
  softmax_1.3:
    width: 1.3
    lr: 1e-3
    wd: 0
  softmax_1.6:
    width: 1.6
    lr: 1e-3
    wd: 0
